### PR TITLE
Update to openssl-1.1.0f

### PR DESCRIPTION
**Pull request by dev5c32373043**

### CODE REVIEW

**Comment by rampr** [comment]
Thanks for the PR. Will there be a change to native-android? I don't think just this change would be sufficient

**Comment by dev5c32373043** [comment]
Hi, i uploaded my game on google play and pass validation also all works pretty well but nothing hinder you test:)

**Comment by rampr** [comment]
Thanks! Could you share the google play link ?
The last time we upgraded openssl, we had to change native-android. Please see this commit -> https://github.com/hashcube/native-android/commit/186675622517e0302902ee9585097871202d737f

Also, how were you able to verify the apk had openssl-1.1.0f built into it ?

**Comment by dev5c32373043** [comment]
warning it's my first game)  https://play.google.com/store/apps/details?id=com.squeezy_studio.squeezy_quantum, for check version need execute unzip -p YourApp.apk | strings | grep "OpenSSL"

**Comment by rampr** [comment]
I just downloaded the APK from Play Store and found it is still OpenSSL 1.0.1s  1 Mar 2016.
Does it have these changes ?

**Comment by rampr** [comment]
Also please check against this script, https://stackoverflow.com/a/24295803. It checks for the OpenSSL versions in any statically linked files. 

You might have to relax the regex to get the results

**Comment by rampr** [comment]
@pickyDude where you able to verify the apk has the desired openssl version?

**Pull request closed without merging**
